# Use official Node image
FROM node:20-slim

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependency install
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose Vite dev server port
EXPOSE 5173
# EZ to remember:
# Roman numeral for 5 = V
# 1 = I <-- in leet1337
# 7 = T
# 3 = E

# Start Vite dev server
CMD ["npm", "run", "dev"]
