server {
    listen 80;
    server_name collab_nginx;

    # Django static files
    location /static/ {
        alias /vol/web/static/; # Matches the volume path defined in your Nginx service
        autoindex off;
    }

    # Vite/React frontend
    # handle routing on the client side, we're not serving django templates
    # Django serves the APIs
    location / {
        root /vol/web/frontend_build/;
        index index.html;
        try_files $uri /index.html;
    }
}